### ISSUE TITLE
Require Strong Date Validation

### ISSUE THREAD

**Issue by xmenxwk** [LSXPrime/Aegis#5]
Just checking DateTime.Now with "greater than" condition is not good idea, a user can set the system date to earlier date and use the software easily.

Edit : Check following answer
https://stackoverflow.com/a/16530146

**Comment by xmenxwk** [comment]
First of all, I like your library. There are some things that needs to be improved. The generation and validation codes should be in separate projects. A licensed app should only have access to validate license only. So the projects should be like this

Aegis // for validating license only
Aegis.Generation //for generating license
Aegis.Server // for both

and about storage or anything specific to platform, add an extra project for each platform, like
Aegis.Windows
Aegis.macOS
I think you already considered that.

And for validating dates, save the data encrypted either in registry or in any file. Should also have some kind of file or data deletion detection. It cant be 100% secured but it should be hard to manipulate as license is being created by server.

**Comment by LSXPrime** [comment]
Thanks for the feedback and for appreciating the library! I'm glad you find it useful.

I appreciate your feedback on the library structure. Separating generation and validation into different projects might seem cleaner at first glance, but as you pointed out, the core logic is quite intricate. The generation code is primarily focused on object creation, with the builder offering convenient setters. Splitting them would introduce unnecessary complexity without substantial benefits.

Regarding platform-specific implementations, your suggestion of creating separate projects (e.g., Aegis.Windows, Aegis.macOS) is valid for large-scale, platform-dependent features. However, in Aegis's case, the core functionality is platform-agnostic. Introducing platform-specific projects for smaller features like secure storage would lead to significant code bloat and make the library less maintainable over time.

That's why I believe that providing a validation helper interface is a better solution. It allows for flexibility in date/time validation and storage while keeping the core library lean and focused. Users can easily implement their custom logic tailored to their specific requirements and platforms. I plan to include a Windows-specific example using the Registry in the "Samples" directory to demonstrate this and offer a starting point for others.


> And for validating dates, save the data encrypted either in registry or in any file. Should also have some kind of file or data deletion detection. It cant be 100% secured but it should be hard to manipulate as license is being created by server.

If the validation was server-side only, then we don't need to worry about DateTime since user can't manipulate the server-side, but locally, if the secret file deleted and there is no internet connection yet, then the license will reset and pass

**Comment by LSXPrime** [comment]
Good morning, Commit [bedccc1](https://github.com/LSXPrime/Aegis/commit/bedccc1686ac696273c24254f7f5bb1485fc2c14) addresses this issue; now developers can create their own custom validation rules And I provided an example [Aegis.Sample.Validation.DateTime.Windows](https://github.com/LSXPrime/Aegis/tree/master/samples/Aegis.Sample.Validation.DateTime.Windows) to prevent tampering license by changing system time on Windows using registry.

Since this issue is addressed, I will close this issue. If you encounter any problems regarding this, don't hesitate to open it again.
