### ISSUE TITLE
Encryption and Decryption

### ISSUE THREAD

**Issue by xmenxwk** [LSXPrime/Aegis#6]
After reading code further I came to realize that private key is required to decrypt the license data, and to do that, we must ship application with both private and public keys. If thats the case, that encryption is not useful. Private key must remain with license generator only and for encrypting the data. The app on client side can decrypt with public key only. Thats the whole point of public and private keys.

**Comment by LSXPrime** [comment]
Thanks for bringing this up! I understand your concern about including the private key with the application. However, the library is designed to use RSA for both encryption and digital signatures, each serving a different purpose in license management.

Here's how it works:

1. **License Encryption:** The license data is encrypted using the developer's public key. This ensures only we can generate valid licenses. Your application decrypts this data using the private key since it's standard for RSA to decrypt with private keys only.

2. **License Signature:** The license data is also digitally signed by the license generator using its own private key. Your application verifies this signature using the license generator's public key, ensuring the license's authenticity and integrity.

As a result, it requires access to the private key in order to decrypt. I am not sure if this is relevant to your point, but it appears that RSA does not permit private key encryption or signing, at least not as of the most recent commit.

I understand your point of view, but I tried to use a public key for decryption, but it looks like .NET cryptography doesn't allow it. To try to resolve this, I made some modifications to the codebase. If you have any suggestions for handling this case, I am open to discussing it.

**Comment by xmenxwk** [comment]
A quick idea of this might work, I might have missed something.

Generator Side
- Get json from class object
- Encrypt Json with AES
- SHA256 Hash AES encrypted data
- Sign SHA256 Hash with RSA Private key
- Create File with Following 3 segments
- SHAHash + SignedSHAHash + AES Encrypted Data


License App Side
- Verify SignedSHAHash with public key
- Verify SHAHash with encrypted data
- Decrypt AES Data

**Comment by LSXPrime** [comment]
Good evening, I pushed a commit with fixes you suggested. If you have the time, you can take a look at the code and tell if it needs any changes.

**Comment by xmenxwk** [comment]
I quickly checked, it looks good. I have one question, LoadLicenseAsync() already did the license file verification, why further verify in ValidateLicenseAsync > ValidateLicenseOffline > ValidateStandardLicense > VerifyLicenseData ?

Also please add LicenseUtils.LoadLicensingSecrets(LicensingSecrets secrets);
