### ISSUE TITLE
Install a Trial license by default

### ISSUE THREAD

**Issue by ThomasWetzel** [LSXPrime/Aegis#8]
Hi,

you did a great job!

I was wondering how to check the evaluation time without installing a trial license at all.
So a user downloads an application and it runs in trial mode automatically for a given amount of time.

Usually you don't enter a trial key to check the functionality of an application (beside Enterprise applications).

Do you have an idea for this need?

Thank you
Thomas

**Comment by LSXPrime** [comment]
Generating trial licenses on the client side is not feasible because it requires the RSA private key used for license signing. Distributing this private key with the application is a security risk and therefore not recommended.

However, if you are managing your licences with Aegis.Server, here is a method to accomplish automatic trial licence creation without sacrificing security:

**1. Server-Side Trial License Generation:**

   - Clone the `Aegis.Server.AspNetCore` sample project.
   - Create a new API endpoint like `/api/licenses/generate-trial` that accepts:
     - Product ID
     - Trial duration
     - (Optional) Any additional data you want to include in the license, like allowed features or hardware ID.
   - This endpoint will use your securely stored private key on the server to generate the trial license.

**2. Client-Side First-Run Logic:**

   - On the first run of your client application, it should send a request to the `/api/licenses/generate-trial` endpoint.
   - Include the necessary information like product ID and trial duration.
   - The server will respond with the generated trial license file (encrypted and signed).
   - The client application then saves this license file locally for future use.

---

Alternatively, you can embed a pre-generated license file within your application and manage license expiration dates using custom validation rule.

**But Since I should permit turning off the built-in validation logic so that it can only rely on custom validation rules, this method would have to wait for the next library update.**

**1. Generate a Pre-Made Trial License:**

   - Create a trial license file with a distant future expiry date. This date doesn't actually matter for validation, as it will be overridden by your custom rule.
   - Embed this license file as a resource in your client application.

**2. Implement a Custom Validation Rule:**

   - Create a custom validation rule that implements `IValidationRule`.
   - In the `Validate` method, check if the license type is "Trial".
   - If it is a trial license:
     - Calculate the actual trial end date based on the application's first start date (which you'll need to store persistently).
     - Compare the current date with the calculated trial end date.
     - Return `true` (valid) if the trial period hasn't expired, otherwise return `false` (invalid) with an appropriate exception (e.g., `ExpiredLicenseException`).

**Comment by ThomasWetzel** [comment]
Hi,

thank you for your detailed answer.

The idea with the license server is a very good idea.

Storing data on a computer that can't be deleted to set back a trial period is not so easy. But with the license server nobody could reset the trial period on its own.

Again, thank you

Thomas
